RightClickFrame.Name = "RightClickFrame"
RightClickFrame.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
RightClickFrame.BorderSizePixel = 2
RightClickFrame.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]+30,COLOR_SCHEME_RAW[2]+30,COLOR_SCHEME_RAW[3]+30)
RightClickFrame.Size = UDim2.new(0,200,0,0)
RightClickFrame.ZIndex = 21000000
Hider.Name = "Hider"
Hider.Parent = RightClickFrame
Hider.AnchorPoint = Vector2.new(0,1)
Hider.Position = UDim2.new(0,0,1,0)
Hider.BackgroundColor3 = Color3.new(0.2, 0.2, 0.2)
Hider.BorderSizePixel = 0
Hider.Size = UDim2.new(1,0,1,0)
Hider.ZIndex = 21000002
ClickSound.SoundId = "rbxassetid://5041171667"
ClickSound.Volume = 1
ClickSound.Parent = SRS
ClickSound2.SoundId = "rbxassetid://876939830"
ClickSound2.Volume = 4
ClickSound2.Parent = SRS
EnterSound.SoundId = "rbxassetid://177266782"
EnterSound.Volume = 1
EnterSound.Parent = SRS
ChangeSound.SoundId = "rbxassetid://4479083227"
ChangeSound.Volume = 1
ChangeSound.Parent = SRS
BeepSound.SoundId = "rbxassetid://138081500"
BeepSound.Volume = 0.5
BeepSound.Parent = SRS
AllFrame.Name = "AllFrame"
AllFrame.Parent = SRS
AllFrame.AnchorPoint = Vector2.new(0.5,0.5)
AllFrame.BackgroundColor3 = COLOR_SCHEME
AllFrame.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
AllFrame.BorderSizePixel = 5
AllFrame.Position = UDim2.new(0.5,0,0.5,0)
AllFrame.Size = UDim2.new(0,850,0,370)
AllFrame.BorderMode = Enum.BorderMode.Inset
AllFrame.ClipsDescendants = true
TitleFrame.Name = "TitleFrame"
TitleFrame.Parent = AllFrame
TitleFrame.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
TitleFrame.BorderSizePixel = 0
TitleFrame.AnchorPoint = Vector2.new(1,0)
TitleFrame.Position = UDim2.new(1,0,0,0)
TitleFrame.Size = UDim2.new(0, 250, 0, 30)
Title.Name = "Title"
Title.Parent = TitleFrame
Title.BackgroundTransparency = 1
Title.Size = UDim2.new(1, 0, 1, 0)
Title.ZIndex = 10
Title.Font = Enum.Font.GothamSemibold
Title.Text = "CheatBlox"
Title.TextColor3 = Color3.new(1, 1, 1)
Title.TextScaled = true
Title.TextSize = 14
Title.TextWrapped = true
TitleShadow.Name = "TitleShadow"
TitleShadow.Parent = TitleFrame
TitleShadow.BackgroundTransparency = 1
TitleShadow.Position = UDim2.new(0, 3, 0, 3)
TitleShadow.Size = UDim2.new(1, 0, 1, 0)
TitleShadow.Font = Enum.Font.GothamSemibold
TitleShadow.Text = "CheatBlox"
TitleShadow.TextColor3 = Color3.new(0, 0, 0)
TitleShadow.TextScaled = true
TitleShadow.TextSize = 14
TitleShadow.TextWrapped = true
Options.Name = "Options"
Options.Parent = AllFrame
Options.BackgroundTransparency = 1
Options.Size = UDim2.new(0, 150, 0, 30)
Options.AutoButtonColor = false
Options.Text = "Menu"
Options.TextColor3 = Color3.new(0,1,0)
Options.TextScaled = true
Options.TextSize = 14
Options.TextWrapped = true
Options.ZIndex = 100000
OptionsShadow.Name = "OptionsShadow"
OptionsShadow.Parent = AllFrame
OptionsShadow.BackgroundTransparency = 1
OptionsShadow.Position = UDim2.new(0, 3, 0, 3)
OptionsShadow.Selectable = true
OptionsShadow.Size = UDim2.new(0, 150, 0, 30)
OptionsShadow.ZIndex = 10000
OptionsShadow.Text = "Menu"
OptionsShadow.TextColor3 = Color3.new(0, 0, 0)
OptionsShadow.TextScaled = true
OptionsShadow.TextSize = 14
OptionsShadow.TextWrapped = true
MainFrame.Name = "MainFrame"
MainFrame.Parent = AllFrame
MainFrame.AnchorPoint = Vector2.new(0, 1)
MainFrame.BackgroundColor3 = COLOR_SCHEME
MainFrame.BorderSizePixel = 0
MainFrame.Position = UDim2.new(0, 0, 1, 0)
MainFrame.Size = UDim2.new(1, 0, 1, -30)
ButtonsFrame.Name = "ButtonsFrame"
ButtonsFrame.Parent = MainFrame
ButtonsFrame.AnchorPoint = Vector2.new(1,1)
ButtonsFrame.BackgroundColor3 = COLOR_SCHEME
ButtonsFrame.BorderColor3 = Color3.fromRGB(0,0,0)
ButtonsFrame.BorderSizePixel = 3
ButtonsFrame.Position = UDim2.new(0, -7, 1, 0)
ButtonsFrame.Size = UDim2.new(0, 150, 1, 0)
ButtonsFrame.ZIndex = 222222
Home.Name = "Home"
Home.Parent = ButtonsFrame
Home.BackgroundTransparency = 1
Home.Size = UDim2.new(1, 0, 0, 30)
Home.AutoButtonColor = false
Home.Text = "Home"
Home.TextColor3 = Color3.new(1, 1, 1)
Home.TextScaled = true
Home.TextSize = 14
Home.TextWrapped = true
Home.ZIndex = 10000000
HomeShadow.Name = "HomeShadow"
HomeShadow.Parent = ButtonsFrame
HomeShadow.BackgroundTransparency = 1
HomeShadow.Position = UDim2.new(0, 3, 0, 3)
HomeShadow.Size = UDim2.new(1, 0, 0, 30)
HomeShadow.ZIndex = 0
HomeShadow.Text = "Home"
HomeShadow.TextColor3 = Color3.new(0, 0, 0)
HomeShadow.TextScaled = true
HomeShadow.TextSize = 14
HomeShadow.TextWrapped = true
HomeShadow.ZIndex = 10000000 - 1
RemoteSpy.Name = "RemoteSpy"
RemoteSpy.Parent = ButtonsFrame
RemoteSpy.BackgroundTransparency = 1
RemoteSpy.Position = UDim2.new(0, 0, 0, 30)
RemoteSpy.Size = UDim2.new(1, 0, 0, 30)
RemoteSpy.AutoButtonColor = false
RemoteSpy.Text = "RemoteSpy"
RemoteSpy.TextColor3 = Color3.new(1, 1, 1)
RemoteSpy.TextScaled = true
RemoteSpy.TextSize = 14
RemoteSpy.TextWrapped = true
RemoteSpy.ZIndex = 10000000
RemoteSpyShadow.Name = "RemoteSpyShadow"
RemoteSpyShadow.Parent = ButtonsFrame
RemoteSpyShadow.BackgroundTransparency = 1
RemoteSpyShadow.Position = UDim2.new(0, 3, 0, 33)
RemoteSpyShadow.Size = UDim2.new(1, 0, 0, 30)
RemoteSpyShadow.ZIndex = 0
RemoteSpyShadow.Text = "RemoteSpy"
RemoteSpyShadow.TextColor3 = Color3.new(0, 0, 0)
RemoteSpyShadow.TextScaled = true
RemoteSpyShadow.TextSize = 14
RemoteSpyShadow.TextWrapped = true
RemoteSpyShadow.ZIndex = 10000000 - 1
Remotes.Name = "Remotes"
Remotes.Parent = ButtonsFrame
Remotes.BackgroundTransparency = 1
Remotes.Position = UDim2.new(0, 0, 0, 90)
Remotes.Size = UDim2.new(1, 0, 0, 30)
Remotes.AutoButtonColor = false
Remotes.Text = "Remotes"
Remotes.TextColor3 = Color3.new(1, 1, 1)
Remotes.TextScaled = true
Remotes.TextSize = 14
Remotes.TextWrapped = true
Remotes.ZIndex = 10000000
RemotesShadow.Name = "RemotesShadow"
RemotesShadow.Parent = ButtonsFrame
RemotesShadow.BackgroundTransparency = 1
RemotesShadow.Position = UDim2.new(0, 3, 0, 93)
RemotesShadow.Size = UDim2.new(1, 0, 0, 30)
RemotesShadow.ZIndex = 0
RemotesShadow.Text = "Remotes"
RemotesShadow.TextColor3 = Color3.new(0, 0, 0)
RemotesShadow.TextScaled = true
RemotesShadow.TextSize = 14
RemotesShadow.TextWrapped = true
RemotesShadow.ZIndex = 10000000 - 1
Namecall.Name = "Namecall"
Namecall.Parent = ButtonsFrame
Namecall.BackgroundTransparency = 1
Namecall.Position = UDim2.new(0, 0, 0, 120)
Namecall.Size = UDim2.new(1, 0, 0, 30)
Namecall.AutoButtonColor = false
Namecall.Text = "Ignored"
Namecall.TextColor3 = Color3.new(1, 1, 1)
Namecall.TextScaled = true
Namecall.TextSize = 14
Namecall.TextWrapped = true
Namecall.ZIndex = 10000000
NamecallShadow.Name = "NamecallShadow"
NamecallShadow.Parent = ButtonsFrame
NamecallShadow.BackgroundTransparency = 1
NamecallShadow.Position = UDim2.new(0, 3, 0, 123)
NamecallShadow.Size = UDim2.new(1, 0, 0, 30)
NamecallShadow.ZIndex = 0
NamecallShadow.Text = "Ignored"
NamecallShadow.TextColor3 = Color3.new(0, 0, 0)
NamecallShadow.TextScaled = true
NamecallShadow.TextSize = 14
NamecallShadow.TextWrapped = true
NamecallShadow.ZIndex = 10000000 - 1
DebugShadow.Name = "DebugShadow"
DebugShadow.Parent = ButtonsFrame
DebugShadow.BackgroundTransparency = 1
DebugShadow.Position = UDim2.new(0, 3, 0, 63)
DebugShadow.Size = UDim2.new(1, 0, 0, 30)
DebugShadow.ZIndex = 0
DebugShadow.Text = "Debug"
DebugShadow.TextColor3 = Color3.new(0, 0, 0)
DebugShadow.TextScaled = true
DebugShadow.TextSize = 14
DebugShadow.TextWrapped = true
DebugShadow.ZIndex = 10000000 - 1
Decompile.Name = "Decompile"
Decompile.Parent = ButtonsFrame
Decompile.BackgroundTransparency = 1
Decompile.Position = UDim2.new(0, 0, 0, 150)
Decompile.Size = UDim2.new(1, 0, 0, 30)
Decompile.AutoButtonColor = false
Decompile.Text = "Decompile"
Decompile.TextColor3 = Color3.new(1, 1, 1)
Decompile.TextScaled = true
Decompile.TextSize = 14
Decompile.TextWrapped = true
Decompile.ZIndex = 10000000
DecompileShadow.Name = "DecompileShadow"
DecompileShadow.Parent = ButtonsFrame
DecompileShadow.BackgroundTransparency = 1
DecompileShadow.Position = UDim2.new(0, 3, 0, 153)
DecompileShadow.Size = UDim2.new(1, 0, 0, 30)
DecompileShadow.ZIndex = 0
DecompileShadow.Text = "Decompile"
DecompileShadow.TextColor3 = Color3.new(0, 0, 0)
DecompileShadow.TextScaled = true
DecompileShadow.TextSize = 14
DecompileShadow.TextWrapped = true
DecompileShadow.ZIndex = 10000000 - 1
Debug.Name = "Debug"
Debug.Parent = ButtonsFrame
Debug.BackgroundTransparency = 1
Debug.Position = UDim2.new(0, 0, 0, 60)
Debug.Size = UDim2.new(1, 0, 0, 30)
Debug.AutoButtonColor = false
Debug.Text = "Debug"
Debug.TextColor3 = Color3.new(1, 1, 1)
Debug.TextScaled = true
Debug.TextSize = 14
Debug.TextWrapped = true
Debug.ZIndex = 10000000
ScriptSpy.Name = "ScriptSpy"
ScriptSpy.Parent = ButtonsFrame
ScriptSpy.BackgroundTransparency = 1
ScriptSpy.Position = UDim2.new(0, 0, 0, 180)
ScriptSpy.Size = UDim2.new(1, 0, 0, 30)
ScriptSpy.AutoButtonColor = false
ScriptSpy.Text = "ScriptSpy"
ScriptSpy.TextColor3 = Color3.new(1,1,1)
ScriptSpy.TextScaled = true
ScriptSpy.TextSize = 14
ScriptSpy.TextWrapped = true
ScriptSpy.ZIndex = 10000000
EnableSrs.Name = "EnableSrs"
EnableSrs.Parent = ButtonsFrame
EnableSrs.BackgroundTransparency = 1
EnableSrs.Position = UDim2.new(0, 0, 0, 240)
EnableSrs.Size = UDim2.new(1, 0, 0, 30)
EnableSrs.AutoButtonColor = false
EnableSrs.Text = "Enabled"
EnableSrs.TextColor3 = Color3.new(0,1,0)
EnableSrs.TextScaled = true
EnableSrs.TextSize = 14
EnableSrs.TextWrapped = true
EnableSrs.ZIndex = 10000000
ScriptSpyShadow.Name = "ScriptSpyShadow"
ScriptSpyShadow.Parent = ButtonsFrame
ScriptSpyShadow.BackgroundTransparency = 1
ScriptSpyShadow.Position = UDim2.new(0, 3, 0, 183)
ScriptSpyShadow.Size = UDim2.new(1, 0, 0, 30)
ScriptSpyShadow.ZIndex = 0
ScriptSpyShadow.Text = "ScriptSpy"
ScriptSpyShadow.TextColor3 = Color3.new(0, 0, 0)
ScriptSpyShadow.TextScaled = true
ScriptSpyShadow.TextSize = 14
ScriptSpyShadow.TextWrapped = true
ScriptSpyShadow.ZIndex = 10000000 - 1
EnableSrsShadow.Name = "EnableSrsShadow"
EnableSrsShadow.Parent = ButtonsFrame
EnableSrsShadow.BackgroundTransparency = 1
EnableSrsShadow.Position = UDim2.new(0, 3, 0, 243)
EnableSrsShadow.Size = UDim2.new(1, 0, 0, 30)
EnableSrsShadow.ZIndex = 0
EnableSrsShadow.Text = "Enabled"
EnableSrsShadow.TextColor3 = Color3.new(0, 0, 0)
EnableSrsShadow.TextScaled = true
EnableSrsShadow.TextSize = 14
EnableSrsShadow.TextWrapped = true
EnableSrsShadow.ZIndex = 10000000 - 1
UpScan.Name = "UpScan"
UpScan.Parent = ButtonsFrame
UpScan.BackgroundTransparency = 1
UpScan.Position = UDim2.new(0, 0, 0, 210)
UpScan.Size = UDim2.new(1, 0, 0, 30)
UpScan.AutoButtonColor = false
UpScan.Text = "Val Finder"
UpScan.TextColor3 = Color3.new(1, 1, 1)
UpScan.TextScaled = true
UpScan.TextSize = 14
UpScan.TextWrapped = true
UpScan.ZIndex = 10000000
UpScanShadow.Name = "UpScanShadow"
UpScanShadow.Parent = ButtonsFrame
UpScanShadow.BackgroundTransparency = 1
UpScanShadow.Position = UDim2.new(0, 3, 0, 213)
UpScanShadow.Size = UDim2.new(1, 0, 0, 30)
UpScanShadow.ZIndex = 0
UpScanShadow.Text = "Val Finder"
UpScanShadow.TextColor3 = Color3.new(0, 0, 0)
UpScanShadow.TextScaled = true
UpScanShadow.TextSize = 14
UpScanShadow.TextWrapped = true
UpScanShadow.ZIndex = 10000000 - 1
Clear.Name = "Clear"
Clear.Parent = ButtonsFrame
Clear.BackgroundTransparency = 1
Clear.Position = UDim2.new(0, 0, 0, 270)
Clear.Size = UDim2.new(1, 0, 0, 30)
Clear.AutoButtonColor = false
Clear.Text = "Clear"
Clear.TextColor3 = Color3.new(1, 1, 1)
Clear.TextScaled = true
Clear.TextSize = 14
Clear.TextWrapped = true
Clear.ZIndex = 10000000
ClearShadow.Name = "ClearShadow"
ClearShadow.Parent = ButtonsFrame
ClearShadow.BackgroundTransparency = 1
ClearShadow.Position = UDim2.new(0, 3, 0, 273)
ClearShadow.Size = UDim2.new(1, 0, 0, 30)
ClearShadow.ZIndex = 0
ClearShadow.Text = "Clear"
ClearShadow.TextColor3 = Color3.new(0, 0, 0)
ClearShadow.TextScaled = true
ClearShadow.TextSize = 14
ClearShadow.TextWrapped = true
ClearShadow.ZIndex = 10000000 - 1
HomeFrame.Name = "HomeFrame"
HomeFrame.Parent = MainFrame
HomeFrame.BackgroundColor3 = COLOR_SCHEME
HomeFrame.BorderSizePixel = 0
HomeFrame.Size = UDim2.new(1, 0, 1, 0)
HomeFrame.Visible = true
NewsText.Name = "News"
NewsText.Parent = HomeFrame
NewsText.BackgroundTransparency = 1
NewsText.Size = UDim2.new(1, 0, 1, 0)
NewsText.Text = [[
F8 to hide/show GUI

Changelog:

[+] CheatBlox will not replace stuff like
game:GetService("Players").ROBLOX.PlayerGui with
game:GetService("Players").LocalPlayer.PlayerGui.
Applies to character aswell.
[*] Fixed nil arguments.

My Discord: Stefan#6965
My Discord Server Code: cRsEhnFqsW
]]
NewsText.TextColor3 = Color3.new(1, 1, 1)
NewsText.TextSize = 25
NewsText.TextYAlignment = Enum.TextYAlignment.Top
NewsText.ZIndex = NewsText.ZIndex + 1
NewsTextShadow.ZIndex = NewsTextShadow.ZIndex - 1
NewsTextShadow.TextColor3 = Color3.new(0,0,0)
NewsTextShadow.Position = NewsTextShadow.Position + UDim2.new(0,3,0,3)
NewsTextShadow.Parent = NewsText.Parent
RemoteSpyFrame.Name = "RemoteSpyFrame"
RemoteSpyFrame.Parent = MainFrame
RemoteSpyFrame.BackgroundColor3 = COLOR_SCHEME
RemoteSpyFrame.BorderSizePixel = 0
RemoteSpyFrame.Size = UDim2.new(1, 0, 1, 0)
RemoteSpyFrame.Visible = false
ScriptSpyFrame.Name = "ScriptSpyFrame"
ScriptSpyFrame.Parent = MainFrame
ScriptSpyFrame.BackgroundColor3 = COLOR_SCHEME
ScriptSpyFrame.BorderSizePixel = 0
ScriptSpyFrame.Size = UDim2.new(1, 0, 1, 0)
ScriptSpyFrame.Visible = false
RemoteLogsList.Name = "RemoteLogsList"
RemoteLogsList.Parent = RemoteSpyFrame
RemoteLogsList.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
RemoteLogsList.BorderSizePixel = 2
RemoteLogsList.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
RemoteLogsList.Size = UDim2.new(0, 196, 1, 0)
RemoteLogsList.ScrollBarThickness = 0
ScriptLogsList.Name = "ScriptLogsList"
ScriptLogsList.Parent = ScriptSpyFrame
ScriptLogsList.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ScriptLogsList.BorderSizePixel = 2
ScriptLogsList.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
ScriptLogsList.Size = UDim2.new(0, 196, 1, 0)
ScriptLogsList.ScrollBarThickness = 0
RemoteSpyMain.Name = "RemoteSpyMain"
RemoteSpyMain.Parent = RemoteSpyFrame
RemoteSpyMain.AnchorPoint = Vector2.new(1, 0)
RemoteSpyMain.BackgroundTransparency = 1
RemoteSpyMain.Position = UDim2.new(1, 0, 0, 0)
RemoteSpyMain.Size = UDim2.new(1, -200, 1, 0)
ScriptSpyMain.Name = "ScriptSpyMain"
ScriptSpyMain.Parent = ScriptSpyFrame
ScriptSpyMain.AnchorPoint = Vector2.new(1, 0)
ScriptSpyMain.BackgroundTransparency = 1
ScriptSpyMain.Position = UDim2.new(1, 0, 0, 0)
ScriptSpyMain.Size = UDim2.new(1, -200, 1, 0)
RemoteSpyText.Name = "RemoteSpyText"
RemoteSpyText.Parent = RemoteSpyMain
RemoteSpyText.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
RemoteSpyText.BorderSizePixel = 2
RemoteSpyText.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
RemoteSpyText.Size = UDim2.new(1, 0, 0, 300)
RemoteSpyText.ClearTextOnFocus = false
RemoteSpyText.MultiLine = true
RemoteSpyText.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
RemoteSpyText.PlaceholderText = "--// Remote Script Here"
RemoteSpyText.Text = ""
RemoteSpyText.TextWrapped = true
RemoteSpyText.TextColor3 = Color3.new(1, 1, 1)
RemoteSpyText.TextSize = 10
RemoteSpyText.TextXAlignment = Enum.TextXAlignment.Left
RemoteSpyText.TextYAlignment = Enum.TextYAlignment.Top
ScriptSpyText.Name = "ScriptSpyText"
ScriptSpyText.Parent = ScriptSpyMain
ScriptSpyText.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ScriptSpyText.BorderSizePixel = 2
ScriptSpyText.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
ScriptSpyText.Size = UDim2.new(1, 0, 0, 300)
ScriptSpyText.ClearTextOnFocus = false
ScriptSpyText.MultiLine = true
ScriptSpyText.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
ScriptSpyText.PlaceholderText = "--// Path To LocalScript Here"
ScriptSpyText.Text = ""
ScriptSpyText.TextColor3 = Color3.new(1, 1, 1)
ScriptSpyText.TextSize = 10
ScriptSpyText.TextWrapped = true
ScriptSpyText.TextXAlignment = Enum.TextXAlignment.Left
ScriptSpyText.TextYAlignment = Enum.TextYAlignment.Top
RemoteFire.Name = "RemoteFire"
RemoteFire.Parent = RemoteSpyMain
RemoteFire.BackgroundTransparency = 1
RemoteFire.Position = UDim2.new(-0, 0, 0, 300)
RemoteFire.Size = UDim2.new(0, 200, 0, 30)
RemoteFire.AutoButtonColor = false
RemoteFire.Text = "Fire Remote"
RemoteFire.TextColor3 = Color3.new(1, 1, 1)
RemoteFire.TextScaled = true
RemoteFire.TextSize = 14
RemoteFire.TextWrapped = true
RemoteFire.ZIndex = 100
RemoteFireShadow.Name = "RemoteFireShadow"
RemoteFireShadow.Parent = RemoteSpyMain
RemoteFireShadow.BackgroundTransparency = 1
RemoteFireShadow.Position = UDim2.new(0, 3, 0, 303)
RemoteFireShadow.Size = UDim2.new(0, 200, 0, 30)
RemoteFireShadow.ZIndex = 99
RemoteFireShadow.Text = "Fire Remote"
RemoteFireShadow.TextColor3 = Color3.new(0, 0, 0)
RemoteFireShadow.TextScaled = true
RemoteFireShadow.TextSize = 14
RemoteFireShadow.TextWrapped = true
SpyScript.Name = "SpyScript"
SpyScript.Parent = ScriptSpyMain
SpyScript.BackgroundTransparency = 1
SpyScript.Position = UDim2.new(-0, 0, 0, 300)
SpyScript.Size = UDim2.new(0, 200, 0, 30)
SpyScript.AutoButtonColor = false
SpyScript.Text = "Spy"
SpyScript.TextColor3 = Color3.new(1, 1, 1)
SpyScript.TextScaled = true
SpyScript.TextSize = 14
SpyScript.TextWrapped = true
SpyScript.ZIndex = 100
SpyScriptShadow.Name = "SpyScriptShadow"
SpyScriptShadow.Parent = ScriptSpyMain
SpyScriptShadow.BackgroundTransparency = 1
SpyScriptShadow.Position = UDim2.new(0, 3, 0, 303)
SpyScriptShadow.Size = UDim2.new(0, 200, 0, 30)
SpyScriptShadow.ZIndex = 99
SpyScriptShadow.Text = "Spy"
SpyScriptShadow.TextColor3 = Color3.new(0, 0, 0)
SpyScriptShadow.TextScaled = true
SpyScriptShadow.TextSize = 14
SpyScriptShadow.TextWrapped = true
UnSpyScript.Name = "UnSpyScript"
UnSpyScript.Parent = ScriptSpyMain
UnSpyScript.BackgroundTransparency = 1
UnSpyScript.Position = UDim2.new(0, 210, 0, 300)
UnSpyScript.Size = UDim2.new(0, 200, 0, 30)
UnSpyScript.AutoButtonColor = false
UnSpyScript.Text = "Unspy"
UnSpyScript.TextColor3 = Color3.new(1, 1, 1)
UnSpyScript.TextScaled = true
UnSpyScript.TextSize = 14
UnSpyScript.TextWrapped = true
UnSpyScript.ZIndex = 100
UnSpyScriptShadow.Name = "UnSpyScriptShadow"
UnSpyScriptShadow.Parent = ScriptSpyMain
UnSpyScriptShadow.BackgroundTransparency = 1
UnSpyScriptShadow.Position = UDim2.new(0, 213, 0, 303)
UnSpyScriptShadow.Size = UDim2.new(0, 200, 0, 30)
UnSpyScriptShadow.ZIndex = 99
UnSpyScriptShadow.Text = "Unspy"
UnSpyScriptShadow.TextColor3 = Color3.new(0, 0, 0)
UnSpyScriptShadow.TextScaled = true
UnSpyScriptShadow.TextSize = 14
UnSpyScriptShadow.TextWrapped = true
IgnoreRemote.Name = "IgnoreRemote"
IgnoreRemote.Parent = RemoteSpyMain
IgnoreRemote.BackgroundTransparency = 1
IgnoreRemote.Position = UDim2.new(0, 210, 0, 300)
IgnoreRemote.Size = UDim2.new(0, 200, 0, 30)
IgnoreRemote.AutoButtonColor = false
IgnoreRemote.Text = "Ignore Remote"
IgnoreRemote.TextColor3 = Color3.new(1, 1, 1)
IgnoreRemote.TextScaled = true
IgnoreRemote.TextSize = 14
IgnoreRemote.TextWrapped = true
IgnoreRemote.ZIndex = 100
IgnoreRemoteCallShadow.Name = "IgnoreRemoteCallShadow"
IgnoreRemoteCallShadow.Parent = RemoteSpyMain
IgnoreRemoteCallShadow.BackgroundTransparency = 1
IgnoreRemoteCallShadow.Position = UDim2.new(0, 423, 0, 303)
IgnoreRemoteCallShadow.Size = UDim2.new(0, 200, 0, 30)
IgnoreRemoteCallShadow.ZIndex = 99
IgnoreRemoteCallShadow.Text = "Ignore Call"
IgnoreRemoteCallShadow.TextColor3 = Color3.new(0, 0, 0)
IgnoreRemoteCallShadow.TextScaled = true
IgnoreRemoteCallShadow.TextSize = 14
IgnoreRemoteCallShadow.TextWrapped = true
IgnoreRemoteCall.Name = "IgnoreRemoteCall"
IgnoreRemoteCall.Parent = RemoteSpyMain
IgnoreRemoteCall.BackgroundTransparency = 1
IgnoreRemoteCall.Position = UDim2.new(0, 420, 0, 300)
IgnoreRemoteCall.Size = UDim2.new(0, 200, 0, 30)
IgnoreRemoteCall.AutoButtonColor = false
IgnoreRemoteCall.Text = "Ignore Call"
IgnoreRemoteCall.TextColor3 = Color3.new(1, 1, 1)
IgnoreRemoteCall.TextScaled = true
IgnoreRemoteCall.TextSize = 14
IgnoreRemoteCall.TextWrapped = true
IgnoreRemoteCall.ZIndex = 100
IgnoreIndCall.Name = "IgnoreIndCall"
IgnoreIndCall.Parent = ScriptSpyMain
IgnoreIndCall.BackgroundTransparency = 1
IgnoreIndCall.Position = UDim2.new(0, 420, 0, 300)
IgnoreIndCall.Size = UDim2.new(0, 200, 0, 30)
IgnoreIndCall.AutoButtonColor = false
IgnoreIndCall.Text = "Ignore Call"
IgnoreIndCall.TextColor3 = Color3.new(1, 1, 1)
IgnoreIndCall.TextScaled = true
IgnoreIndCall.TextSize = 14
IgnoreIndCall.TextWrapped = true
IgnoreIndCall.ZIndex = 100
IgnoreIndCallShadow.Name = "IgnoreRemoteShadow"
IgnoreIndCallShadow.Parent = ScriptSpyMain
IgnoreIndCallShadow.BackgroundTransparency = 1
IgnoreIndCallShadow.Position = UDim2.new(0, 423, 0, 303)
IgnoreIndCallShadow.Size = UDim2.new(0, 200, 0, 30)
IgnoreIndCallShadow.ZIndex = 99
IgnoreIndCallShadow.Text = "Ignore Call"
IgnoreIndCallShadow.TextColor3 = Color3.new(0, 0, 0)
IgnoreIndCallShadow.TextScaled = true
IgnoreIndCallShadow.TextSize = 14
IgnoreIndCallShadow.TextWrapped = true
IgnoreRemoteShadow.Name = "IgnoreRemoteShadow"
IgnoreRemoteShadow.Parent = RemoteSpyMain
IgnoreRemoteShadow.BackgroundTransparency = 1
IgnoreRemoteShadow.Position = UDim2.new(0, 213, 0, 303)
IgnoreRemoteShadow.Size = UDim2.new(0, 200, 0, 30)
IgnoreRemoteShadow.ZIndex = 99
IgnoreRemoteShadow.Text = "Ignore Remote"
IgnoreRemoteShadow.TextColor3 = Color3.new(0, 0, 0)
IgnoreRemoteShadow.TextScaled = true
IgnoreRemoteShadow.TextSize = 14
IgnoreRemoteShadow.TextWrapped = true
DecompilerFrame.Name = "DecompilerFrame"
DecompilerFrame.Parent = MainFrame
DecompilerFrame.BackgroundColor3 = COLOR_SCHEME
DecompilerFrame.BorderSizePixel = 0
DecompilerFrame.Size = UDim2.new(1, 0, 1, 0)
DecompilerFrame.Visible = false
DecompilerText.Name = "DecompilerText"
DecompilerText.Parent = DecompilerFrame
DecompilerText.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
DecompilerText.BorderSizePixel = 2
DecompilerText.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
DecompilerText.Size = UDim2.new(1, 0, 1, 0)
DecompilerText.ClearTextOnFocus = false
DecompilerText.MultiLine = true
DecompilerText.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
DecompilerText.PlaceholderText = "--// Decompiled Script Here"
DecompilerText.Text = ""
DecompilerText.TextColor3 = Color3.new(1, 1, 1)
DecompilerText.TextSize = 20
DecompilerText.TextXAlignment = Enum.TextXAlignment.Left
DecompilerText.TextYAlignment = Enum.TextYAlignment.Top
RemotesFrame.Name = "RemotesFrame"
RemotesFrame.Parent = MainFrame
RemotesFrame.BackgroundColor3 = COLOR_SCHEME
RemotesFrame.BorderSizePixel = 0
RemotesFrame.Size = UDim2.new(1, 0, 1, 0)
RemotesFrame.Visible = false
ChangerFrame.Name = "ChangerFrame"
ChangerFrame.Parent = MainFrame
ChangerFrame.BackgroundColor3 = COLOR_SCHEME
ChangerFrame.BorderSizePixel = 0
ChangerFrame.Size = UDim2.new(1, 0, 1, 0)
ChangerFrame.Visible = false
ChangerMain.Name = "ChangerMain"
ChangerMain.Parent = ChangerFrame
ChangerMain.AnchorPoint = Vector2.new(1, 0)
ChangerMain.BackgroundTransparency = 1
ChangerMain.Position = UDim2.new(1, 0, 0, 0)
ChangerMain.Size = UDim2.new(1, -200, 1, 0)
SFor.Name = "SFor"
SFor.Parent = ChangerMain
SFor.BackgroundTransparency = 1
SFor.Position = UDim2.new(0, 55, 0, 0)
SFor.Size = UDim2.new(0, 200, 0, 50)
SFor.ZIndex = 100
SFor.Text = "Search for..."
SFor.TextColor3 = Color3.new(1, 1, 1)
SFor.TextScaled = true
SFor.TextSize = 14
SFor.TextWrapped = true
SForBox.Name = "SForBox"
SForBox.Parent = ChangerMain
SForBox.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
SForBox.BorderSizePixel = 2
SForBox.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
SForBox.Position = UDim2.new(0.5,0, 0, 100)
SForBox.Size = UDim2.new(0, 300, 0, 60)
SForBox.ClearTextOnFocus = false
SForBox.MultiLine = true
SForBox.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
SForBox.PlaceholderText = "eg: \"ammo\", 123"
SForBox.Text = ""
SForBox.TextColor3 = Color3.new(1, 1, 1)
SForBox.AnchorPoint = Vector2.new(0.5,0.5)
SForBox.TextSize = 15
TypeTextBox.Name = "TypeTextBox"
TypeTextBox.Parent = ChangerMain
TypeTextBox.AnchorPoint = Vector2.new(0.5,0.5)
TypeTextBox.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
TypeTextBox.BorderSizePixel = 2
TypeTextBox.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
TypeTextBox.Position = UDim2.new(0.5,0, 0, 170)
TypeTextBox.Size = UDim2.new(0, 300, 0, 60)
TypeTextBox.ClearTextOnFocus = false
TypeTextBox.MultiLine = true
TypeTextBox.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
TypeTextBox.PlaceholderText = "eg:upvalue,global,prop,table"
TypeTextBox.Text = ""
TypeTextBox.TextColor3 = Color3.new(1, 1, 1)
TypeTextBox.TextSize = 15
SearchButton.Name = "SearchButton"
SearchButton.AnchorPoint = Vector2.new(0.5,0.5)
SearchButton.Parent = ChangerMain
SearchButton.BackgroundTransparency = 1
SearchButton.Position = UDim2.new(0.5,0,0,300)
SearchButton.Size = UDim2.new(0, 200, 0, 30)
SearchButton.ZIndex = 100
SearchButton.AutoButtonColor = false
SearchButton.Text = "Search"
SearchButton.TextColor3 = Color3.new(1, 1, 1)
SearchButton.TextScaled = true
SearchButton.TextSize = 14
SearchButton.TextWrapped = true
SearchButtonShadow.Name = "SearchButtonShadow"
SearchButtonShadow.Parent = ChangerMain
SearchButtonShadow.BackgroundTransparency = 1
SearchButtonShadow.AnchorPoint = Vector2.new(0.5,0.5)
SearchButtonShadow.Position = UDim2.new(0.5,3,0,303)
SearchButtonShadow.Size = UDim2.new(0, 200, 0, 30)
SearchButtonShadow.ZIndex = 99
SearchButtonShadow.Text = "Search"
SearchButtonShadow.TextColor3 = Color3.new(0, 0, 0)
SearchButtonShadow.TextScaled = true
SearchButtonShadow.TextSize = 14
SearchButtonShadow.TextWrapped = true
ChangerLogsList.Name = "ChangerLogsList"
ChangerLogsList.Parent = ChangerFrame
ChangerLogsList.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ChangerLogsList.BorderSizePixel = 2
ChangerLogsList.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
ChangerLogsList.Size = UDim2.new(0, 200, 1, 0)
ChangerLogsList.ScrollBarThickness = 0
SForShadow.Name = "SForShadow"
SForShadow.Parent = ChangerMain
SForShadow.BackgroundTransparency = 1
SForShadow.Position = UDim2.new(0, 58, 0, 3)
SForShadow.Size = UDim2.new(0, 200, 0, 50)
SForShadow.ZIndex = 99
SForShadow.Text = "Search for..."
SForShadow.TextColor3 = Color3.new(0, 0, 0)
SForShadow.TextScaled = true
SForShadow.TextSize = 14
SForShadow.TextWrapped = true
RemotesList.Name = "RemotesList"
RemotesList.Parent = RemotesFrame
RemotesList.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
RemotesList.BorderSizePixel = 0
RemotesList.Size = UDim2.new(1, 0, 1, 0)
RemotesList.ScrollBarThickness = 0
Overlay.Name = "Overlay"
Overlay.Parent = MainFrame
Overlay.BackgroundColor3 = Color3.new(0, 0, 0)
Overlay.BackgroundTransparency = 0.7
Overlay.BorderSizePixel = 0
Overlay.Size = UDim2.new(0, 0, 1, 0)
Overlay.ZIndex = 222
NamecallFrame.Name = "NamecallFrame"
NamecallFrame.Parent = MainFrame
NamecallFrame.BackgroundColor3 = COLOR_SCHEME
NamecallFrame.BorderSizePixel = 0
NamecallFrame.Size = UDim2.new(1, 0, 1, 0)
NamecallFrame.Visible = false
NamecallLogsList.Name = "NamecallLogsList"
NamecallLogsList.Parent = NamecallFrame
NamecallLogsList.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
NamecallLogsList.BorderSizePixel = 2
NamecallLogsList.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
NamecallLogsList.Size = UDim2.new(0, 196, 1, 0)
NamecallLogsList.ScrollBarThickness = 0
NamecallMain.Name = "NamecallMain"
NamecallMain.Parent = NamecallFrame
NamecallMain.AnchorPoint = Vector2.new(1, 0)
NamecallMain.BackgroundTransparency = 1
NamecallMain.Position = UDim2.new(1, 0, 0, 0)
NamecallMain.Size = UDim2.new(1, -200, 1, 0)
NamecallText.Name = "NamecallText"
NamecallText.Parent = NamecallMain
NamecallText.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
NamecallText.BorderSizePixel = 2
NamecallText.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
NamecallText.Size = UDim2.new(1, 0, 0, 300)
NamecallText.ClearTextOnFocus = false
NamecallText.MultiLine = true
NamecallText.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
NamecallText.PlaceholderText = "--// Namecall Info Here"
NamecallText.Text = ""
NamecallText.TextColor3 = Color3.new(1, 1, 1)
NamecallText.TextSize = 20
NamecallText.TextXAlignment = Enum.TextXAlignment.Left
NamecallText.TextYAlignment = Enum.TextYAlignment.Top
EnableNamecall.Name = "EnableNamecall"
EnableNamecall.Parent = NamecallMain
EnableNamecall.BackgroundTransparency = 1
EnableNamecall.Position = UDim2.new(0, 0, 0, 300)
EnableNamecall.Size = UDim2.new(0, 200, 0, 30)
EnableNamecall.AutoButtonColor = false
EnableNamecall.Text = "Enable"
EnableNamecall.TextColor3 = Color3.new(0, 1, 0)
EnableNamecall.TextScaled = true
EnableNamecall.TextSize = 14
EnableNamecall.TextWrapped = true
EnableNamecall.ZIndex = 100
EnableNamecallShadow.Name = "EnableNamecallShadow"
EnableNamecallShadow.Parent = NamecallMain
EnableNamecallShadow.BackgroundTransparency = 1
EnableNamecallShadow.Position = UDim2.new(0, 3, 0, 303)
EnableNamecallShadow.Size = UDim2.new(0, 200, 0, 30)
EnableNamecallShadow.ZIndex = 99
EnableNamecallShadow.Text = "Enable"
EnableNamecallShadow.TextColor3 = Color3.new(0, 0, 0)
EnableNamecallShadow.TextScaled = true
EnableNamecallShadow.TextSize = 14
EnableNamecallShadow.TextWrapped = true
DebugFrame.Name = "DebugFrame"
DebugFrame.Parent = MainFrame
DebugFrame.BackgroundColor3 = COLOR_SCHEME
DebugFrame.BorderSizePixel = 0
DebugFrame.Size = UDim2.new(1, 0, 1, 0)
DebugFrame.Visible = false
DebugLogsList.Name = "DebugLogsList"
DebugLogsList.Parent = DebugFrame
DebugLogsList.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
DebugLogsList.BorderSizePixel = 2
DebugLogsList.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
DebugLogsList.Size = UDim2.new(0, 200, 1, 0)
DebugLogsList.ScrollBarThickness = 0
DebugMain.Name = "DebugMain"
DebugMain.Parent = DebugFrame
DebugMain.AnchorPoint = Vector2.new(1, 0)
DebugMain.BackgroundTransparency = 1
DebugMain.Position = UDim2.new(1, 0, 0, 0)
DebugMain.Size = UDim2.new(1, -200, 1, 0)
CText.Name = "CText"
CText.Parent = DebugMain
CText.BackgroundTransparency = 1
CText.Position = UDim2.new(0, 230, 0, 0)
CText.Size = UDim2.new(0, 180, 0, 50)
CText.Text = "Constants:"
CText.TextColor3 = Color3.new(1, 1, 1)
CText.TextScaled = true
CText.TextSize = 14
CText.TextWrapped = true
CText.ZIndex = 100
UTextShadow.Name = "UTextShadow"
UTextShadow.Parent = DebugMain
UTextShadow.BackgroundTransparency = 1
UTextShadow.Position = UDim2.new(0, 28, 0, 3)
UTextShadow.Size = UDim2.new(0, 180, 0, 50)
UTextShadow.ZIndex = 99
UTextShadow.Text = "Upvalues:"
UTextShadow.TextColor3 = Color3.new(0, 0, 0)
UTextShadow.TextScaled = true
UTextShadow.TextSize = 14
UTextShadow.TextWrapped = true
ULogs.Name = "ULogs"
ULogs.Parent = DebugMain
ULogs.AnchorPoint = Vector2.new(0, 1)
ULogs.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ULogs.BorderSizePixel = 2
ULogs.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
ULogs.Position = UDim2.new(0, 25, 1, 0)
ULogs.Size = UDim2.new(0, 180, 1, -50)
ULogs.ScrollBarThickness = 0
CLogs.Name = "CLogs"
CLogs.Parent = DebugMain
CLogs.AnchorPoint = Vector2.new(0, 1)
CLogs.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
CLogs.BorderSizePixel = 2
CLogs.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
CLogs.Position = UDim2.new(0, 230, 1, 0)
CLogs.Size = UDim2.new(0, 180, 1, -50)
CLogs.ScrollBarThickness = 0
UText.Name = "UText"
UText.Parent = DebugMain
UText.BackgroundTransparency = 1
UText.Position = UDim2.new(0, 25, 0, 0)
UText.Size = UDim2.new(0, 180, 0, 50)
UText.Text = "Upvalues:"
UText.TextColor3 = Color3.new(1, 1, 1)
UText.TextScaled = true
UText.TextSize = 14
UText.TextWrapped = true
UText.ZIndex = 100
EText.Name = "EText"
EText.Parent = DebugMain
EText.BackgroundTransparency = 1
EText.Position = UDim2.new(0, 435, 0, 0)
EText.Size = UDim2.new(0, 180, 0, 50)
EText.Text = "Env:"
EText.TextColor3 = Color3.new(1, 1, 1)
EText.TextScaled = true
EText.TextSize = 14
EText.TextWrapped = true
EText.ZIndex = 100
ELogs.Name = "ELogs"
ELogs.Parent = DebugMain
ELogs.AnchorPoint = Vector2.new(0, 1)
ELogs.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ELogs.BorderSizePixel = 2
ELogs.BorderColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
ELogs.Position = UDim2.new(0, 435, 1, 0)
ELogs.Size = UDim2.new(0, 180, 1, -50)
ELogs.ScrollBarThickness = 0
ETextShadow.Name = "CTextShadow"
ETextShadow.Parent = DebugMain
ETextShadow.BackgroundTransparency = 1
ETextShadow.Position = UDim2.new(0, 438, 0, 3)
ETextShadow.Size = UDim2.new(0, 180, 0, 50)
ETextShadow.ZIndex = 99
ETextShadow.Text = "Env:"
ETextShadow.TextColor3 = Color3.new(0, 0, 0)
ETextShadow.TextScaled = true
ETextShadow.TextSize = 14
ETextShadow.TextWrapped = true
CTextShadow.Name = "CTextShadow"
CTextShadow.Parent = DebugMain
CTextShadow.BackgroundTransparency = 1
CTextShadow.Position = UDim2.new(0, 233, 0, 3)
CTextShadow.Size = UDim2.new(0, 180, 0, 50)
CTextShadow.ZIndex = 99
CTextShadow.Text = "Constants:"
CTextShadow.TextColor3 = Color3.new(0, 0, 0)
CTextShadow.TextScaled = true
CTextShadow.TextSize = 14
CTextShadow.TextWrapped = true
Darkness.Name = "Darkness"
Darkness.Parent = MainFrame
Darkness.BackgroundColor3 = Color3.new(0, 0, 0)
Darkness.BorderSizePixel = 0
Darkness.Size = UDim2.new(0, 0, 1, 0)
Darkness.ZIndex = 99999999
RemoteLog.Name = "RemoteLog"
RemoteLog.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-30,COLOR_SCHEME_RAW[2]-30,COLOR_SCHEME_RAW[3]-30)
RemoteLog.BackgroundTransparency = 0
RemoteLog.Size = UDim2.new(1, -2, 0, 30)
RemoteLog.Text = ""
RemoteLog.TextColor3 = Color3.new(1, 1, 0)
RemoteLog.BorderColor3 = Color3.new(1, 1, 0)
RemoteLog.BorderMode = Enum.BorderMode.Inset
RemoteLog.TextScaled = true
RemoteLog.TextWrapped = true
RemoteLog.ZIndex = 222221
RemoteLogShadow.Name = "RemoteLogShadow"
RemoteLogShadow.BackgroundTransparency = 1
RemoteLogShadow.Position = UDim2.new(0, 3, 0, 3)
RemoteLogShadow.Size = UDim2.new(1, 0, 0, 30)
RemoteLogShadow.ZIndex = 0
RemoteLogShadow.Text = "???"
RemoteLogShadow.TextColor3 = Color3.new(0, 0, 0)
RemoteLogShadow.TextScaled = true
RemoteLogShadow.TextWrapped = true
RemoteLogShadow.ZIndex = RemoteLog.ZIndex - 1
ValChangerFrame.Name = "ValChangerFrame"
ValChangerFrame.Visible = false
ValChangerFrame.Parent = SRS
ValChangerFrame.AnchorPoint = Vector2.new(0.5, 0.5)
ValChangerFrame.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ValChangerFrame.BorderColor3 = Color3.new(0, 0, 0)
ValChangerFrame.BorderSizePixel = 3
ValChangerFrame.Position = UDim2.new(0.5, 0, 0.5, 0)
ValChangerFrame.Size = UDim2.new(0, 500, 0, 300)
ValChangerFrame.ZIndex = 999999
ChangerLabel.Name = "ChangerLabel"
ChangerLabel.Parent = ValChangerFrame
ChangerLabel.BackgroundTransparency = 1
ChangerLabel.Selectable = true
ChangerLabel.Size = UDim2.new(1, 0, 0, 50)
ChangerLabel.ZIndex = -1
ChangerLabel.Font = Enum.Font.SourceSans
ChangerLabel.Text = "X Changer"
ChangerLabel.TextColor3 = Color3.new(1, 1, 1)
ChangerLabel.TextScaled = true
ChangerLabel.TextSize = 14
ChangerLabel.TextWrapped = true
ChangerLabelShadow.Name = "ChangerLabelShadow"
ChangerLabelShadow.Parent = ValChangerFrame
ChangerLabelShadow.BackgroundTransparency = 1
ChangerLabelShadow.Position = UDim2.new(0, 3, 0, 3)
ChangerLabelShadow.Selectable = true
ChangerLabelShadow.Size = UDim2.new(1, 0, 0, 50)
ChangerLabelShadow.ZIndex = -1
ChangerLabelShadow.Font = Enum.Font.SourceSans
ChangerLabelShadow.Text = "X Changer"
ChangerLabelShadow.TextColor3 = Color3.new(0, 0, 0)
ChangerLabelShadow.TextScaled = true
ChangerLabelShadow.TextSize = 14
ChangerLabelShadow.TextWrapped = true
ValChangerBox.Name = "ValChangerBox"
ValChangerBox.Parent = ValChangerFrame
ValChangerBox.AnchorPoint = Vector2.new(0.5, 1)
ValChangerBox.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
ValChangerBox.BorderColor3 = Color3.new(0, 0, 0)
ValChangerBox.BorderSizePixel = 2
ValChangerBox.Position = UDim2.new(0.5, 0, 0.899999976, 0)
ValChangerBox.Size = UDim2.new(0.800000012, 0, 0, 50)
ValChangerBox.Font = Enum.Font.SourceSans
ValChangerBox.PlaceholderText = "Enter new value here"
ValChangerBox.Text = ""
ValChangerBox.TextColor3 = Color3.new(0, 0, 0)
ValChangerBox.TextSize = 20
ValChangerBox.ZIndex = -1
PrevValLabel.Name = "PrevValLabel"
PrevValLabel.Parent = ValChangerFrame
PrevValLabel.AnchorPoint = Vector2.new(0.5, 1)
PrevValLabel.BackgroundColor3 = Color3.fromRGB(COLOR_SCHEME_RAW[1]-20,COLOR_SCHEME_RAW[2]-20,COLOR_SCHEME_RAW[3]-20)
PrevValLabel.BorderColor3 = Color3.new(0, 0, 0)
PrevValLabel.BorderSizePixel = 2
PrevValLabel.Position = UDim2.new(0.5, 0, 0.5, 0)
PrevValLabel.Size = UDim2.new(0.800000012, 0, 0, 50)
PrevValLabel.Font = Enum.Font.SourceSans
PrevValLabel.Text = "Loading..."
PrevValLabel.TextColor3 = Color3.new(0, 0, 0)
PrevValLabel.TextSize = 20
PrevValLabel.ZIndex = 0
